version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStr0ng@2025!
    ports:
      - "1433:1433"
    networks:
      - sql_network

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge

# docker-compose up -d
# docker-compose stop
# docker-compose start
# docker-compose down
# docker-compose down --volumes